(() => {
  'use strict';
  const VAPID_KEY='BGZHOWnnMHSGeBnC3pETHWRAu84UFL7yBZBq74Uxoc2xAfBPySP3XuTolheQHJqG_CxgZYNX6-hSZuA5XHDqJXc',MESSAGING_SDK='https://www.gstatic.com/firebasejs/9.23.0/firebase-messaging-compat.js',TOKEN_STORAGE_KEY='opex_fcm_token_v1',TOKEN_SYNC_KEY='opex_fcm_token_synced_v1';let messaging=null,initPromise=null;
  function installMobileHeaderFix(){if(document.getElementById('opex-mobile-header-fix'))return;const style=document.createElement('style');style.id='opex-mobile-header-fix';style.textContent='@media (max-width:820px),(orientation:landscape) and (max-height:600px) and (max-width:1180px){nav{height:auto!important;min-height:0!important;display:flex!important;align-items:center!important;flex-wrap:wrap!important;gap:6px 8px!important;padding:8px 10px!important;overflow:visible!important;z-index:200!important}.brand{order:1!important;flex:1 1 calc(100% - 52px)!important;min-width:0!important}.userbox{order:2!important;margin-left:auto!important;z-index:220!important}.tabs{order:3!important;display:flex!important;flex:0 0 100%!important;width:100%!important;overflow-x:auto!important;gap:4px!important;padding:4px 0 1px!important}.tab{flex:0 0 auto!important;min-height:46px!important;padding:7px 10px!important;font-size:10px!important}.dropdown{position:fixed!important;top:62px!important;right:8px!important;width:min(290px,calc(100vw - 16px))!important;z-index:9999!important}}';document.head.appendChild(style);}
  function notify(m,e=false){if(typeof window.toast==='function')return window.toast(m,e);console[e?'error':'log']('[OpEx Push]',m)}
  function loadModule(src,marker,errorText){if(document.querySelector(`script[data-${marker}]`))return;const s=document.createElement('script');s.src=src;s.async=true;s.setAttribute(`data-${marker}`,'true');s.onerror=()=>console.error(errorText);document.head.appendChild(s)}
  function loadCommentsModule(){loadModule('./comments-v1.js?v=40','opex-comments-v1','[OpEx] Kunne ikke laste comments-v1.js')}function loadActivityModule(){loadModule('./activity-v1.js?v=40','opex-activity-v1','[OpEx] Kunne ikke laste activity-v1.js')}function loadQuickCreateModule(){loadModule('./quick-create-v1.js?v=41','opex-quick-create-v1','[OpEx] Kunne ikke laste quick-create-v1.js')}
  function loadMessagingSdk(){if(window.firebase?.messaging)return Promise.resolve();return new Promise((resolve,reject)=>{const e=document.querySelector(`script[src="${MESSAGING_SDK}"]`);if(e){if(window.firebase?.messaging)return resolve();e.addEventListener('load',resolve,{once:true});e.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=MESSAGING_SDK;s.async=true;s.onload=resolve;s.onerror=()=>reject(new Error('Kunne ikke laste Firebase Messaging SDK'));document.head.appendChild(s)})}
  async function tokenKey(token){if(window.crypto?.subtle){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}return btoa(token).replace(/[.#$\[\]/]/g,'_').slice(0,120)}
  async function saveToken(token){localStorage.setItem(TOKEN_STORAGE_KEY,token);localStorage.setItem(TOKEN_SYNC_KEY,'false');const user=firebase.auth().currentUser;if(!user)throw new Error('Ingen innlogget bruker');const k=await tokenKey(token);await firebase.database().ref(`pushTokens/${user.uid}/${k}`).set({token,uid:user.uid,email:user.email||'',userAgent:navigator.userAgent,platform:navigator.userAgentData?.platform||navigator.platform||'',permission:Notification.permission,updatedAt:new Date().toISOString(),appVersion:'push-v1a'});localStorage.setItem(TOKEN_SYNC_KEY,'true')}
  function updateButtons(){const e=document.getElementById('pushEnableButton'),c=document.getElementById('pushCopyButton');if(!e)return;const t=localStorage.getItem(TOKEN_STORAGE_KEY);if(!('Notification'in window)){e.textContent='🔕 Push støttes ikke her';e.disabled=true;if(c)c.style.display='none';return}if(Notification.permission==='granted'&&t){e.textContent=localStorage.getItem(TOKEN_SYNC_KEY)==='true'?'🔔 Varsler er aktivert':'🔔 Varsler aktivert – synkroniser';if(c)c.style.display='block'}else if(Notification.permission==='denied'){e.textContent='🔕 Varsler er blokkert i nettleseren';if(c)c.style.display=t?'block':'none'}else{e.textContent='🔔 Aktiver varsler';if(c)c.style.display=t?'block':'none'}}
  function ensureButtons(){const d=document.getElementById('drop');if(!d||document.getElementById('pushEnableButton'))return;const e=document.createElement('button');e.id='pushEnableButton';e.className='dropitem';e.type='button';e.onclick=x=>{x.stopPropagation();enablePushNotifications()};const c=document.createElement('button');c.id='pushCopyButton';c.className='dropitem';c.type='button';c.textContent='🧪 Kopier push-token';c.style.display='none';c.onclick=x=>{x.stopPropagation();copyPushToken()};const a=document.getElementById('adminDrop');d.insertBefore(e,a||null);d.insertBefore(c,a||null);updateButtons()}
  async function initMessaging(){if(initPromise)return initPromise;initPromise=(async()=>{if(!window.isSecureContext)throw new Error('Push krever HTTPS');await loadMessagingSdk();messaging=firebase.messaging();messaging.onMessage(p=>notify(`${p?.notification?.title||p?.data?.title||'OpEx Hub'}: ${p?.notification?.body||p?.data?.body||'Du har et nytt varsel.'}`));return messaging})().catch(e=>{initPromise=null;throw e});return initPromise}
  async function enablePushNotifications(){try{if(!firebase.auth().currentUser)return notify('Logg inn før du aktiverer varsler.',true);const p=await Notification.requestPermission();if(p!=='granted'){updateButtons();return notify('Varsler ble ikke aktivert.',true)}const i=await initMessaging(),r=await navigator.serviceWorker.ready,t=await i.getToken({vapidKey:VAPID_KEY,serviceWorkerRegistration:r});if(!t)throw new Error('Firebase returnerte ikke et push-token');try{await saveToken(t);notify('Push-varsler er aktivert på denne enheten 🔔')}catch(e){localStorage.setItem(TOKEN_STORAGE_KEY,t);notify('Push er aktivert lokalt, men token kunne ikke lagres i Firebase.',true)}updateButtons()}catch(e){notify('Kunne ikke aktivere push: '+(e?.message||'ukjent feil'),true)}}
  async function copyPushToken(){const t=localStorage.getItem(TOKEN_STORAGE_KEY);if(!t)return notify('Ingen push-token er registrert på denne enheten ennå.',true);try{await navigator.clipboard.writeText(t);notify('Push-token kopiert ✓')}catch{window.prompt('Kopier push-token:',t)}}
  async function refreshExistingToken(user){if(!user||Notification.permission!=='granted')return;const t=localStorage.getItem(TOKEN_STORAGE_KEY);if(!t)return;try{await saveToken(t)}catch(e){console.warn('[OpEx Push] Existing token could not be synced:',e)}updateButtons()}
  function bootPush(){installMobileHeaderFix();loadCommentsModule();loadActivityModule();loadQuickCreateModule();ensureButtons();if(!window.firebase?.auth)return;firebase.auth().onAuthStateChanged(u=>{if(u){ensureButtons();refreshExistingToken(u)}updateButtons()})}
  window.enablePushNotifications=enablePushNotifications;window.copyPushToken=copyPushToken;window.__opexPushV1A={enablePushNotifications,copyPushToken};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootPush,{once:true});else bootPush();
})();